type: StakerList
stakers:
- type: Staker
  tag: my_mainnet_staker
  address: '0x00001234'
  private_key: 0x0000xxxx
  chain_id: 1
- type: Staker
  tag: my_rinkeby_staker
  address: '0x00005678'
  private_key: 0x0000xxxx
  chain_id: 4
